dist: bionic
language: generic

install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.sh
    && chmod +x cmake-3.14.5-Linux-x86_64.sh
  - mkdir -p /opt/cmake-3.14.5 && ./cmake-3.14.5-Linux-x86_64.sh --skip-license --prefix=/opt/cmake-3.14.5
  - PATH=/opt/cmake-3.14.5/bin:$PATH
  - wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2
  - tar xf gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 -C /opt
  - mkdir build && cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/gcc-arm-none-eabi-8-2019-q3-update.cmake
  - make

before_deploy:
  - tar cvzf candleLight_fw_${TRAVIS_TAG}.tar.gz $(ls *_fw*)

deploy:
  provider: releases
  api_key:
    github-token: $GITHUB_TOKEN
  edge: true
  file:
    - candleLight_fw_${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: candle-usb/candleLight_fw
    branch: master
